services:
  postgres:
    image: postgres
    container_name: shopapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5435:5432'
    networks:
      - default

  shopapp-backend:
    container_name: shopapp-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5435
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123456
    networks:
      - default

networks:
  default:
    name: shopapp-backend

volumes:
  postgres: